#!/bin/bash
#
# 00_Build_Cluster
#
# Copyright (C) 2013-2015, Levyx, Inc.
#
# NOTICE:  All information contained herein is, and remains the property of
# Levyx, Inc.  The intellectual and technical concepts contained herein are
# proprietary to Levyx, Inc. and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material is
# strictly forbidden unless prior written permission is obtained from Levyx,
# Inc.  Access to the source code contained herein is hereby forbidden to
# anyone except current Levyx, Inc. employees, managers or contractors who
# have executed Confidentiality and Non-disclosure agreements explicitly
# covering such access.
#

echo "Running $0"
[ -z $VM_PREFIX ] && echo "needs -n or --name" && exit -1
[ ! -e  ./levyx/common.sh ] && echo "Can not find common.sh! Exit -1" && exit -1
set +x; source ./levyx/common.sh; ((DEBUG_FLAG)) && set -x
show_gcloud_instances "Pre deployment instances"
verify_env_file
verify_input
save_env
upload_env

checkout_bdutil
generate_bdutil_config
run_bdutil_create
show_gcloud_instances "Post building VMs"
run_bdutil_deploy
RC=$?
echo "RC=$RC"

sudo_cluster $CHANGE_MNT_OWNERSHIP
set +e; sudo_cluster $RESIZE_PARTITION; set -e;
sudo_cluster $CHANGE_SYSCTL_FSLIMIT
sudo_cluster $CHANGE_SECLIMITS_FSLIMIT
reset_cluster
sudo_cluster $RESIZE_FS

((CLI_CLEANUP_FLG)) && clean_up
show_gcloud_instances "Afrer modifying the boot disk size!"
echo "Finished running $0"
